#include "FileExporter.h"
#include <QFile>
#include <QTextStream>
#include <QClipboard>
#include <QApplication>
#include <QPrinter>
#include <QTextDocument>
#include <QDebug>

bool FileExporter::exportToTXT(const QString& text, const QString& filepath) {
    QFile file(filepath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qWarning() << "Failed to open file for writing:" << filepath;
        return false;
    }
    
    QTextStream out(&file);
    out.setCodec("UTF-8");
    out << text;
    file.close();
    
    qDebug() << "Exported to TXT:" << filepath;
    return true;
}

bool FileExporter::exportToDOCX(const QString& text, const QString& filepath) {
    // Basic DOCX is just a ZIP file with XML files
    // For simplicity, we'll generate a basic .docx compatible XML
    // A production app would use libdocx or similar library
    
    QFile file(filepath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qWarning() << "Failed to open file for writing:" << filepath;
        return false;
    }
    
    // For Phase 2, we'll create a simple RTF file disguised as DOCX
    // Most word processors can open it
    QString docxContent = wrapDOCXText(text);
    
    QTextStream out(&file);
    out << docxContent;
    file.close();
    
    qDebug() << "Exported to DOCX:" << filepath;
    return true;
}

bool FileExporter::exportToPDF(const QString& text, const QString& filepath) {
    QPrinter printer(QPrinter::HighResolution);
    printer.setOutputFormat(QPrinter::PdfFormat);
    printer.setOutputFileName(filepath);
    printer.setPageSize(QPrinter::A4);
    
    // Set margins (works across Qt 5.12-5.15)
    QMarginsF margins(15, 15, 15, 15);
    printer.setPageMargins(margins, QPageLayout::Millimeter);
    
    QTextDocument document;
    document.setDefaultFont(QFont("Arial", 12));
    document.setPlainText(text);
    
    // Add a header
    QString htmlContent = QString(
        "<html><body>"
        "<h2 style='text-align: center;'>Speech Transcription</h2>"
        "<p style='font-size: 10pt; color: #666; text-align: center;'>Generated by Speech Recorder - SparklyLabz</p>"
        "<hr>"
        "<p style='font-size: 12pt; line-height: 1.6;'>%1</p>"
        "</body></html>"
    ).arg(text.toHtmlEscaped().replace("\n", "<br>"));
    
    document.setHtml(htmlContent);
    document.print(&printer);
    
    qDebug() << "Exported to PDF:" << filepath;
    return true;
}

void FileExporter::copyToClipboard(const QString& text) {
    QClipboard* clipboard = QApplication::clipboard();
    clipboard->setText(text);
    qDebug() << "Copied" << text.length() << "characters to clipboard";
}

QString FileExporter::wrapDOCXText(const QString& text) {
    // Simple RTF format that most word processors can open
    QString rtf = "{\\rtf1\\ansi\\deff0\n";
    rtf += "{\\fonttbl{\\f0 Times New Roman;}}\n";
    rtf += "{\\colortbl;\\red0\\green0\\blue0;\\red128\\green128\\blue128;}\n";
    rtf += "\\viewkind4\\uc1\\pard\\f0\\fs24\n";
    
    // Header
    rtf += "{\\b\\fs32\\qc Speech Transcription\\par}\n";
    rtf += "{\\fs20\\cf2\\qc Generated by Speech Recorder - SparklyLabz\\par}\n";
    rtf += "\\pard\\par\\par\n";
    
    // Content - escape special RTF characters
    QString escapedText = text;
    escapedText.replace("\\", "\\\\");
    escapedText.replace("{", "\\{");
    escapedText.replace("}", "\\}");
    escapedText.replace("\n", "\\par\n");
    
    rtf += escapedText;
    rtf += "\\par}\n";
    
    return rtf;
}

